[serial]
baudrate = 9600
timeout = 2


[command]
query = *IDN?
reset = *RST
clear = *CLS
error = SYST:ERR?
set_function = FUNC {value}
get_function = FUNC?
set_frequency = FREQ {value}
get_frequency = FREQ?
set_amplitude = VOLT {value}
get_amplitude = VOLT?
set_offset = VOLT:OFFS {value}
get_offset = VOLT:OFFS?
; Duty cycle applies to square wave; use PULS:DCYC for pulse waveform
set_duty = FUNC:SQU:DCYC {value}
get_duty = FUNC:SQU:DCYC?
output_on = OUTP ON
output_off = OUTP OFF
output_state = OUTP?
